import { FranchiseBadgeDef } from "@/lib/types/franchiseBadges.types";

/**
 * Base de Franquias Lendárias com lista de jogos oficiais e requisitos de conclusão.
 * Cada jogo finalizado no catálogo do usuário acende o progresso da insígnia correspondente.
 */
export const OFFICIAL_FRANCHISE_BADGES: FranchiseBadgeDef[] = [
  {
    id: "dark_souls",
    name: "Dark Souls Saga",
    tagline: "Prepare to Die & Link the Fire",
    category: "soulsborne",
    iconName: "Flame",
    accentColor: "#ef4444",
    games: [
      { id: "ds1", title: "Dark Souls Remastered", platformTag: "Multi" },
      { id: "ds2", title: "Dark Souls II: Scholar of the First Sin", platformTag: "Multi" },
      { id: "ds3", title: "Dark Souls III", platformTag: "Multi" },
      { id: "demon_souls", title: "Demon's Souls", platformTag: "PlayStation" },
      { id: "elden_ring", title: "Elden Ring", platformTag: "Multi" },
      { id: "bloodborne", title: "Bloodborne", platformTag: "PlayStation" },
    ],
    minGamesForBronze: 1,
    minGamesForSilver: 2,
    minGamesForGold: 4,
    minGamesForPlat: 6,
  },
  {
    id: "resident_evil",
    name: "Resident Evil Legacy",
    tagline: "Survival Horror & Raccoon City Survivor",
    category: "horror",
    iconName: "Biohazard",
    accentColor: "#10b981",
    games: [
      { id: "re1", title: "Resident Evil HD Remaster", platformTag: "Multi" },
      { id: "re2", title: "Resident Evil 2 Remake", platformTag: "Multi" },
      { id: "re3", title: "Resident Evil 3 Remake", platformTag: "Multi" },
      { id: "re4", title: "Resident Evil 4 Remake", platformTag: "Multi" },
      { id: "re7", title: "Resident Evil 7: Biohazard", platformTag: "Multi" },
      { id: "re8", title: "Resident Evil Village", platformTag: "Multi" },
    ],
    minGamesForBronze: 1,
    minGamesForSilver: 2,
    minGamesForGold: 4,
    minGamesForPlat: 6,
  },
  {
    id: "persona",
    name: "Persona & Velvet Room",
    tagline: "Take Your Heart & Awaken Your Persona",
    category: "rpg",
    iconName: "Sparkles",
    accentColor: "#f43f5e",
    games: [
      { id: "p3r", title: "Persona 3 Reload", platformTag: "Multi" },
      { id: "p4g", title: "Persona 4 Golden", platformTag: "Multi" },
      { id: "p5r", title: "Persona 5 Royal", platformTag: "Multi" },
      { id: "p5s", title: "Persona 5 Strikers", platformTag: "Multi" },
      { id: "p3p", title: "Persona 3 Portable", platformTag: "Multi" },
    ],
    minGamesForBronze: 1,
    minGamesForSilver: 2,
    minGamesForGold: 3,
    minGamesForPlat: 5,
  },
  {
    id: "god_of_war",
    name: "God of War Pantheon",
    tagline: "Ghost of Sparta to Norse Protector",
    category: "action",
    iconName: "Axe",
    accentColor: "#38bdf8",
    games: [
      { id: "gow_2018", title: "God of War (2018)", platformTag: "PlayStation/PC" },
      { id: "gow_ragnarok", title: "God of War Ragnarök", platformTag: "PlayStation/PC" },
      { id: "gow_3", title: "God of War III Remastered", platformTag: "PlayStation" },
      { id: "gow_1", title: "God of War", platformTag: "PlayStation" },
      { id: "gow_2", title: "God of War II", platformTag: "PlayStation" },
    ],
    minGamesForBronze: 1,
    minGamesForSilver: 2,
    minGamesForGold: 3,
    minGamesForPlat: 5,
  },
  {
    id: "zelda",
    name: "The Legend of Zelda",
    tagline: "Courage, Wisdom and the Triforce",
    category: "adventure",
    iconName: "Sword",
    accentColor: "#eab308",
    games: [
      { id: "botw", title: "The Legend of Zelda: Breath of the Wild", platformTag: "Nintendo" },
      { id: "totk", title: "The Legend of Zelda: Tears of the Kingdom", platformTag: "Nintendo" },
      { id: "oot", title: "The Legend of Zelda: Ocarina of Time", platformTag: "Nintendo" },
      { id: "mm", title: "The Legend of Zelda: Majora's Mask", platformTag: "Nintendo" },
      { id: "alttp", title: "The Legend of Zelda: A Link to the Past", platformTag: "Nintendo" },
    ],
    minGamesForBronze: 1,
    minGamesForSilver: 2,
    minGamesForGold: 3,
    minGamesForPlat: 5,
  },
];
